version: '3.0'
services:
  sp-comp-test:
    image: crjoaoribeiro.azurecr.io/spring-boot-docker-complete
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod, smtp #, https
    WEBsite_ENABLE_APP_SERVICE_STORAGE: TRUE
    volumes:
      - compose-fs:/app/data
      - compose-fs-config:/app/config:ro
volumes:
  compose-fs:
    driver: azure_file
    driver_opts:
      share_name: compose-fs
      storage_account_name: sajoaoribeiro
  compose-fs-config:
    driver: azure_file
    driver_opts:
      share_name: compose-fs-config
      storage_account_name: sajoaoribeiro
